// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.1
// source: api/shop/v1/cat.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CatInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CatId   uint64 `protobuf:"varint,1,opt,name=cat_id,json=catId,proto3" json:"cat_id,omitempty"`
	CatName string `protobuf:"bytes,2,opt,name=cat_name,json=catName,proto3" json:"cat_name,omitempty"`
	Pid     uint64 `protobuf:"varint,3,opt,name=pid,proto3" json:"pid,omitempty"`
}

func (x *CatInfo) Reset() {
	*x = CatInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_shop_v1_cat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CatInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatInfo) ProtoMessage() {}

func (x *CatInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_shop_v1_cat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CatInfo.ProtoReflect.Descriptor instead.
func (*CatInfo) Descriptor() ([]byte, []int) {
	return file_api_shop_v1_cat_proto_rawDescGZIP(), []int{0}
}

func (x *CatInfo) GetCatId() uint64 {
	if x != nil {
		return x.CatId
	}
	return 0
}

func (x *CatInfo) GetCatName() string {
	if x != nil {
		return x.CatName
	}
	return ""
}

func (x *CatInfo) GetPid() uint64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type CreateCatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CatName string `protobuf:"bytes,1,opt,name=cat_name,json=catName,proto3" json:"cat_name,omitempty"`
	Pid     uint64 `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
}

func (x *CreateCatRequest) Reset() {
	*x = CreateCatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_shop_v1_cat_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCatRequest) ProtoMessage() {}

func (x *CreateCatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_shop_v1_cat_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCatRequest.ProtoReflect.Descriptor instead.
func (*CreateCatRequest) Descriptor() ([]byte, []int) {
	return file_api_shop_v1_cat_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCatRequest) GetCatName() string {
	if x != nil {
		return x.CatName
	}
	return ""
}

func (x *CreateCatRequest) GetPid() uint64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type CreateCatReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cat *CatInfo `protobuf:"bytes,1,opt,name=cat,proto3" json:"cat,omitempty"`
}

func (x *CreateCatReply) Reset() {
	*x = CreateCatReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_shop_v1_cat_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCatReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCatReply) ProtoMessage() {}

func (x *CreateCatReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_shop_v1_cat_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCatReply.ProtoReflect.Descriptor instead.
func (*CreateCatReply) Descriptor() ([]byte, []int) {
	return file_api_shop_v1_cat_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCatReply) GetCat() *CatInfo {
	if x != nil {
		return x.Cat
	}
	return nil
}

type UpdateCatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cat *CatInfo `protobuf:"bytes,1,opt,name=cat,proto3" json:"cat,omitempty"`
}

func (x *UpdateCatRequest) Reset() {
	*x = UpdateCatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_shop_v1_cat_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateCatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCatRequest) ProtoMessage() {}

func (x *UpdateCatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_shop_v1_cat_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCatRequest.ProtoReflect.Descriptor instead.
func (*UpdateCatRequest) Descriptor() ([]byte, []int) {
	return file_api_shop_v1_cat_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateCatRequest) GetCat() *CatInfo {
	if x != nil {
		return x.Cat
	}
	return nil
}

type UpdateCatReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cat *CatInfo `protobuf:"bytes,1,opt,name=cat,proto3" json:"cat,omitempty"`
}

func (x *UpdateCatReply) Reset() {
	*x = UpdateCatReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_shop_v1_cat_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateCatReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCatReply) ProtoMessage() {}

func (x *UpdateCatReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_shop_v1_cat_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCatReply.ProtoReflect.Descriptor instead.
func (*UpdateCatReply) Descriptor() ([]byte, []int) {
	return file_api_shop_v1_cat_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateCatReply) GetCat() *CatInfo {
	if x != nil {
		return x.Cat
	}
	return nil
}

type DeleteCatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CatId uint64 `protobuf:"varint,1,opt,name=cat_id,json=catId,proto3" json:"cat_id,omitempty"`
}

func (x *DeleteCatRequest) Reset() {
	*x = DeleteCatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_shop_v1_cat_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteCatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCatRequest) ProtoMessage() {}

func (x *DeleteCatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_shop_v1_cat_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCatRequest.ProtoReflect.Descriptor instead.
func (*DeleteCatRequest) Descriptor() ([]byte, []int) {
	return file_api_shop_v1_cat_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteCatRequest) GetCatId() uint64 {
	if x != nil {
		return x.CatId
	}
	return 0
}

type DeleteCatReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *DeleteCatReply) Reset() {
	*x = DeleteCatReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_shop_v1_cat_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteCatReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCatReply) ProtoMessage() {}

func (x *DeleteCatReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_shop_v1_cat_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCatReply.ProtoReflect.Descriptor instead.
func (*DeleteCatReply) Descriptor() ([]byte, []int) {
	return file_api_shop_v1_cat_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteCatReply) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type GetCatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CatId uint64 `protobuf:"varint,1,opt,name=cat_id,json=catId,proto3" json:"cat_id,omitempty"`
}

func (x *GetCatRequest) Reset() {
	*x = GetCatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_shop_v1_cat_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCatRequest) ProtoMessage() {}

func (x *GetCatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_shop_v1_cat_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCatRequest.ProtoReflect.Descriptor instead.
func (*GetCatRequest) Descriptor() ([]byte, []int) {
	return file_api_shop_v1_cat_proto_rawDescGZIP(), []int{7}
}

func (x *GetCatRequest) GetCatId() uint64 {
	if x != nil {
		return x.CatId
	}
	return 0
}

type GetCatReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cat *CatInfo `protobuf:"bytes,1,opt,name=cat,proto3" json:"cat,omitempty"`
}

func (x *GetCatReply) Reset() {
	*x = GetCatReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_shop_v1_cat_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCatReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCatReply) ProtoMessage() {}

func (x *GetCatReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_shop_v1_cat_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCatReply.ProtoReflect.Descriptor instead.
func (*GetCatReply) Descriptor() ([]byte, []int) {
	return file_api_shop_v1_cat_proto_rawDescGZIP(), []int{8}
}

func (x *GetCatReply) GetCat() *CatInfo {
	if x != nil {
		return x.Cat
	}
	return nil
}

type ListCatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListCatRequest) Reset() {
	*x = ListCatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_shop_v1_cat_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCatRequest) ProtoMessage() {}

func (x *ListCatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_shop_v1_cat_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCatRequest.ProtoReflect.Descriptor instead.
func (*ListCatRequest) Descriptor() ([]byte, []int) {
	return file_api_shop_v1_cat_proto_rawDescGZIP(), []int{9}
}

type ListCatReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*CatInfo `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *ListCatReply) Reset() {
	*x = ListCatReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_shop_v1_cat_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCatReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCatReply) ProtoMessage() {}

func (x *ListCatReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_shop_v1_cat_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCatReply.ProtoReflect.Descriptor instead.
func (*ListCatReply) Descriptor() ([]byte, []int) {
	return file_api_shop_v1_cat_proto_rawDescGZIP(), []int{10}
}

func (x *ListCatReply) GetList() []*CatInfo {
	if x != nil {
		return x.List
	}
	return nil
}

var File_api_shop_v1_cat_proto protoreflect.FileDescriptor

var file_api_shop_v1_cat_proto_rawDesc = []byte{
	0x0a, 0x15, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x68, 0x6f, 0x70, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x61,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x68, 0x6f,
	0x70, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x4d, 0x0a, 0x07, 0x43, 0x61, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x15, 0x0a,
	0x06, 0x63, 0x61, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x63,
	0x61, 0x74, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x61, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x70, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x70, 0x69,
	0x64, 0x22, 0x3f, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x61, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x61, 0x74, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x70, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x70,
	0x69, 0x64, 0x22, 0x38, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x61, 0x74, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x26, 0x0a, 0x03, 0x63, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x68, 0x6f, 0x70, 0x2e, 0x76, 0x31, 0x2e,
	0x43, 0x61, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x03, 0x63, 0x61, 0x74, 0x22, 0x3a, 0x0a, 0x10,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x26, 0x0a, 0x03, 0x63, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x73, 0x68, 0x6f, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61, 0x74, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x03, 0x63, 0x61, 0x74, 0x22, 0x38, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x43, 0x61, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x26, 0x0a, 0x03, 0x63, 0x61,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x68,
	0x6f, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x03, 0x63,
	0x61, 0x74, 0x22, 0x29, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x61, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x63, 0x61, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x63, 0x61, 0x74, 0x49, 0x64, 0x22, 0x28, 0x0a,
	0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x61, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x26, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x43, 0x61,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x63, 0x61, 0x74, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x63, 0x61, 0x74, 0x49, 0x64, 0x22,
	0x35, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x43, 0x61, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x26,
	0x0a, 0x03, 0x63, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x73, 0x68, 0x6f, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61, 0x74, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x03, 0x63, 0x61, 0x74, 0x22, 0x10, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x61,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x38, 0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74,
	0x43, 0x61, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x28, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x68, 0x6f,
	0x70, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x6c, 0x69,
	0x73, 0x74, 0x32, 0xbc, 0x03, 0x0a, 0x03, 0x43, 0x61, 0x74, 0x12, 0x55, 0x0a, 0x09, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x43, 0x61, 0x74, 0x12, 0x1d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x68,
	0x6f, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x61, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x68, 0x6f,
	0x70, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x61, 0x74, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x0c, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x06, 0x22, 0x04, 0x2f, 0x63, 0x61,
	0x74, 0x12, 0x55, 0x0a, 0x09, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x61, 0x74, 0x12, 0x1d,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x68, 0x6f, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x43, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x73, 0x68, 0x6f, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x43, 0x61, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x0c, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x06, 0x22, 0x04, 0x2f, 0x63, 0x61, 0x74, 0x12, 0x5e, 0x0a, 0x09, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x43, 0x61, 0x74, 0x12, 0x1d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x68, 0x6f, 0x70,
	0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x61, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x68, 0x6f, 0x70, 0x2e,
	0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x61, 0x74, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x15, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0f, 0x22, 0x0d, 0x2f, 0x63, 0x61, 0x74, 0x2f,
	0x7b, 0x63, 0x61, 0x74, 0x5f, 0x69, 0x64, 0x7d, 0x12, 0x55, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x43,
	0x61, 0x74, 0x12, 0x1a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x68, 0x6f, 0x70, 0x2e, 0x76, 0x31,
	0x2e, 0x47, 0x65, 0x74, 0x43, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x68, 0x6f, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74,
	0x43, 0x61, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x15, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0f,
	0x12, 0x0d, 0x2f, 0x63, 0x61, 0x74, 0x2f, 0x7b, 0x63, 0x61, 0x74, 0x5f, 0x69, 0x64, 0x7d, 0x12,
	0x50, 0x0a, 0x07, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x61, 0x74, 0x12, 0x1b, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x73, 0x68, 0x6f, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x61, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x68,
	0x6f, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x61, 0x74, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x0d, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x07, 0x12, 0x05, 0x2f, 0x63, 0x61, 0x74,
	0x73, 0x42, 0x25, 0x0a, 0x0b, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x68, 0x6f, 0x70, 0x2e, 0x76, 0x31,
	0x50, 0x01, 0x5a, 0x14, 0x73, 0x68, 0x6f, 0x70, 0x70, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x68,
	0x6f, 0x70, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_shop_v1_cat_proto_rawDescOnce sync.Once
	file_api_shop_v1_cat_proto_rawDescData = file_api_shop_v1_cat_proto_rawDesc
)

func file_api_shop_v1_cat_proto_rawDescGZIP() []byte {
	file_api_shop_v1_cat_proto_rawDescOnce.Do(func() {
		file_api_shop_v1_cat_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_shop_v1_cat_proto_rawDescData)
	})
	return file_api_shop_v1_cat_proto_rawDescData
}

var file_api_shop_v1_cat_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_shop_v1_cat_proto_goTypes = []interface{}{
	(*CatInfo)(nil),          // 0: api.shop.v1.CatInfo
	(*CreateCatRequest)(nil), // 1: api.shop.v1.CreateCatRequest
	(*CreateCatReply)(nil),   // 2: api.shop.v1.CreateCatReply
	(*UpdateCatRequest)(nil), // 3: api.shop.v1.UpdateCatRequest
	(*UpdateCatReply)(nil),   // 4: api.shop.v1.UpdateCatReply
	(*DeleteCatRequest)(nil), // 5: api.shop.v1.DeleteCatRequest
	(*DeleteCatReply)(nil),   // 6: api.shop.v1.DeleteCatReply
	(*GetCatRequest)(nil),    // 7: api.shop.v1.GetCatRequest
	(*GetCatReply)(nil),      // 8: api.shop.v1.GetCatReply
	(*ListCatRequest)(nil),   // 9: api.shop.v1.ListCatRequest
	(*ListCatReply)(nil),     // 10: api.shop.v1.ListCatReply
}
var file_api_shop_v1_cat_proto_depIdxs = []int32{
	0,  // 0: api.shop.v1.CreateCatReply.cat:type_name -> api.shop.v1.CatInfo
	0,  // 1: api.shop.v1.UpdateCatRequest.cat:type_name -> api.shop.v1.CatInfo
	0,  // 2: api.shop.v1.UpdateCatReply.cat:type_name -> api.shop.v1.CatInfo
	0,  // 3: api.shop.v1.GetCatReply.cat:type_name -> api.shop.v1.CatInfo
	0,  // 4: api.shop.v1.ListCatReply.list:type_name -> api.shop.v1.CatInfo
	1,  // 5: api.shop.v1.Cat.CreateCat:input_type -> api.shop.v1.CreateCatRequest
	3,  // 6: api.shop.v1.Cat.UpdateCat:input_type -> api.shop.v1.UpdateCatRequest
	5,  // 7: api.shop.v1.Cat.DeleteCat:input_type -> api.shop.v1.DeleteCatRequest
	7,  // 8: api.shop.v1.Cat.GetCat:input_type -> api.shop.v1.GetCatRequest
	9,  // 9: api.shop.v1.Cat.ListCat:input_type -> api.shop.v1.ListCatRequest
	2,  // 10: api.shop.v1.Cat.CreateCat:output_type -> api.shop.v1.CreateCatReply
	4,  // 11: api.shop.v1.Cat.UpdateCat:output_type -> api.shop.v1.UpdateCatReply
	6,  // 12: api.shop.v1.Cat.DeleteCat:output_type -> api.shop.v1.DeleteCatReply
	8,  // 13: api.shop.v1.Cat.GetCat:output_type -> api.shop.v1.GetCatReply
	10, // 14: api.shop.v1.Cat.ListCat:output_type -> api.shop.v1.ListCatReply
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_api_shop_v1_cat_proto_init() }
func file_api_shop_v1_cat_proto_init() {
	if File_api_shop_v1_cat_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_shop_v1_cat_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CatInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_shop_v1_cat_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_shop_v1_cat_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCatReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_shop_v1_cat_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateCatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_shop_v1_cat_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateCatReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_shop_v1_cat_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteCatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_shop_v1_cat_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteCatReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_shop_v1_cat_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_shop_v1_cat_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCatReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_shop_v1_cat_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListCatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_shop_v1_cat_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListCatReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_shop_v1_cat_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_shop_v1_cat_proto_goTypes,
		DependencyIndexes: file_api_shop_v1_cat_proto_depIdxs,
		MessageInfos:      file_api_shop_v1_cat_proto_msgTypes,
	}.Build()
	File_api_shop_v1_cat_proto = out.File
	file_api_shop_v1_cat_proto_rawDesc = nil
	file_api_shop_v1_cat_proto_goTypes = nil
	file_api_shop_v1_cat_proto_depIdxs = nil
}
