// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.1
// source: api/shop/v1/mqproducer.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Products struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProductId   int64  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductName string `protobuf:"bytes,2,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
}

func (x *Products) Reset() {
	*x = Products{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_shop_v1_mqproducer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Products) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Products) ProtoMessage() {}

func (x *Products) ProtoReflect() protoreflect.Message {
	mi := &file_api_shop_v1_mqproducer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Products.ProtoReflect.Descriptor instead.
func (*Products) Descriptor() ([]byte, []int) {
	return file_api_shop_v1_mqproducer_proto_rawDescGZIP(), []int{0}
}

func (x *Products) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *Products) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

type CreateMqproducerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Products *Products `protobuf:"bytes,1,opt,name=products,proto3" json:"products,omitempty"`
}

func (x *CreateMqproducerRequest) Reset() {
	*x = CreateMqproducerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_shop_v1_mqproducer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMqproducerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMqproducerRequest) ProtoMessage() {}

func (x *CreateMqproducerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_shop_v1_mqproducer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMqproducerRequest.ProtoReflect.Descriptor instead.
func (*CreateMqproducerRequest) Descriptor() ([]byte, []int) {
	return file_api_shop_v1_mqproducer_proto_rawDescGZIP(), []int{1}
}

func (x *CreateMqproducerRequest) GetProducts() *Products {
	if x != nil {
		return x.Products
	}
	return nil
}

type CreateMqproducerReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	MqId   int64 `protobuf:"varint,2,opt,name=mq_id,json=mqId,proto3" json:"mq_id,omitempty"`
}

func (x *CreateMqproducerReply) Reset() {
	*x = CreateMqproducerReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_shop_v1_mqproducer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMqproducerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMqproducerReply) ProtoMessage() {}

func (x *CreateMqproducerReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_shop_v1_mqproducer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMqproducerReply.ProtoReflect.Descriptor instead.
func (*CreateMqproducerReply) Descriptor() ([]byte, []int) {
	return file_api_shop_v1_mqproducer_proto_rawDescGZIP(), []int{2}
}

func (x *CreateMqproducerReply) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CreateMqproducerReply) GetMqId() int64 {
	if x != nil {
		return x.MqId
	}
	return 0
}

type UpdateMqproducerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateMqproducerRequest) Reset() {
	*x = UpdateMqproducerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_shop_v1_mqproducer_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMqproducerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMqproducerRequest) ProtoMessage() {}

func (x *UpdateMqproducerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_shop_v1_mqproducer_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMqproducerRequest.ProtoReflect.Descriptor instead.
func (*UpdateMqproducerRequest) Descriptor() ([]byte, []int) {
	return file_api_shop_v1_mqproducer_proto_rawDescGZIP(), []int{3}
}

type UpdateMqproducerReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateMqproducerReply) Reset() {
	*x = UpdateMqproducerReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_shop_v1_mqproducer_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMqproducerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMqproducerReply) ProtoMessage() {}

func (x *UpdateMqproducerReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_shop_v1_mqproducer_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMqproducerReply.ProtoReflect.Descriptor instead.
func (*UpdateMqproducerReply) Descriptor() ([]byte, []int) {
	return file_api_shop_v1_mqproducer_proto_rawDescGZIP(), []int{4}
}

type DeleteMqproducerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteMqproducerRequest) Reset() {
	*x = DeleteMqproducerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_shop_v1_mqproducer_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMqproducerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMqproducerRequest) ProtoMessage() {}

func (x *DeleteMqproducerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_shop_v1_mqproducer_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMqproducerRequest.ProtoReflect.Descriptor instead.
func (*DeleteMqproducerRequest) Descriptor() ([]byte, []int) {
	return file_api_shop_v1_mqproducer_proto_rawDescGZIP(), []int{5}
}

type DeleteMqproducerReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteMqproducerReply) Reset() {
	*x = DeleteMqproducerReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_shop_v1_mqproducer_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMqproducerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMqproducerReply) ProtoMessage() {}

func (x *DeleteMqproducerReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_shop_v1_mqproducer_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMqproducerReply.ProtoReflect.Descriptor instead.
func (*DeleteMqproducerReply) Descriptor() ([]byte, []int) {
	return file_api_shop_v1_mqproducer_proto_rawDescGZIP(), []int{6}
}

type GetMqproducerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetMqproducerRequest) Reset() {
	*x = GetMqproducerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_shop_v1_mqproducer_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMqproducerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMqproducerRequest) ProtoMessage() {}

func (x *GetMqproducerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_shop_v1_mqproducer_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMqproducerRequest.ProtoReflect.Descriptor instead.
func (*GetMqproducerRequest) Descriptor() ([]byte, []int) {
	return file_api_shop_v1_mqproducer_proto_rawDescGZIP(), []int{7}
}

type GetMqproducerReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetMqproducerReply) Reset() {
	*x = GetMqproducerReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_shop_v1_mqproducer_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMqproducerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMqproducerReply) ProtoMessage() {}

func (x *GetMqproducerReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_shop_v1_mqproducer_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMqproducerReply.ProtoReflect.Descriptor instead.
func (*GetMqproducerReply) Descriptor() ([]byte, []int) {
	return file_api_shop_v1_mqproducer_proto_rawDescGZIP(), []int{8}
}

type ListMqproducerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListMqproducerRequest) Reset() {
	*x = ListMqproducerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_shop_v1_mqproducer_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListMqproducerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMqproducerRequest) ProtoMessage() {}

func (x *ListMqproducerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_shop_v1_mqproducer_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMqproducerRequest.ProtoReflect.Descriptor instead.
func (*ListMqproducerRequest) Descriptor() ([]byte, []int) {
	return file_api_shop_v1_mqproducer_proto_rawDescGZIP(), []int{9}
}

type ListMqproducerReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListMqproducerReply) Reset() {
	*x = ListMqproducerReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_shop_v1_mqproducer_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListMqproducerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMqproducerReply) ProtoMessage() {}

func (x *ListMqproducerReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_shop_v1_mqproducer_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMqproducerReply.ProtoReflect.Descriptor instead.
func (*ListMqproducerReply) Descriptor() ([]byte, []int) {
	return file_api_shop_v1_mqproducer_proto_rawDescGZIP(), []int{10}
}

var File_api_shop_v1_mqproducer_proto protoreflect.FileDescriptor

var file_api_shop_v1_mqproducer_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x68, 0x6f, 0x70, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x71,
	0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b,
	0x61, 0x70, 0x69, 0x2e, 0x73, 0x68, 0x6f, 0x70, 0x2e, 0x76, 0x31, 0x22, 0x4c, 0x0a, 0x08, 0x70,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x4c, 0x0a, 0x17, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x4d, 0x71, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x31, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x68, 0x6f,
	0x70, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x52, 0x08, 0x70,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x22, 0x44, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x4d, 0x71, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x13, 0x0a, 0x05, 0x6d, 0x71, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x6d, 0x71, 0x49, 0x64, 0x22, 0x19, 0x0a,
	0x17, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x71, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x17, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x4d, 0x71, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x19, 0x0a, 0x17, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x71, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x17, 0x0a, 0x15,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x71, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x16, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x4d, 0x71, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x14, 0x0a,
	0x12, 0x47, 0x65, 0x74, 0x4d, 0x71, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x17, 0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x71, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x15, 0x0a, 0x13,
	0x4c, 0x69, 0x73, 0x74, 0x4d, 0x71, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x32, 0xd3, 0x03, 0x0a, 0x0a, 0x4d, 0x71, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x65, 0x72, 0x12, 0x5c, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x71, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x12, 0x24, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x68, 0x6f,
	0x70, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x71, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x73, 0x68, 0x6f, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x4d, 0x71, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x5c, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x71, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x65, 0x72, 0x12, 0x24, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x68, 0x6f, 0x70, 0x2e,
	0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x71, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x73, 0x68, 0x6f, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d,
	0x71, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x5c,
	0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x71, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x65, 0x72, 0x12, 0x24, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x68, 0x6f, 0x70, 0x2e, 0x76, 0x31,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x71, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73,
	0x68, 0x6f, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x71, 0x70,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x53, 0x0a, 0x0d,
	0x47, 0x65, 0x74, 0x4d, 0x71, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x12, 0x21, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x73, 0x68, 0x6f, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4d,
	0x71, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x68, 0x6f, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x47,
	0x65, 0x74, 0x4d, 0x71, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x56, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x71, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x65, 0x72, 0x12, 0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x68, 0x6f, 0x70, 0x2e, 0x76,
	0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x71, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x68,
	0x6f, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x71, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x25, 0x0a, 0x0b, 0x61, 0x70, 0x69,
	0x2e, 0x73, 0x68, 0x6f, 0x70, 0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x14, 0x73, 0x68, 0x6f, 0x70,
	0x70, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x68, 0x6f, 0x70, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_shop_v1_mqproducer_proto_rawDescOnce sync.Once
	file_api_shop_v1_mqproducer_proto_rawDescData = file_api_shop_v1_mqproducer_proto_rawDesc
)

func file_api_shop_v1_mqproducer_proto_rawDescGZIP() []byte {
	file_api_shop_v1_mqproducer_proto_rawDescOnce.Do(func() {
		file_api_shop_v1_mqproducer_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_shop_v1_mqproducer_proto_rawDescData)
	})
	return file_api_shop_v1_mqproducer_proto_rawDescData
}

var file_api_shop_v1_mqproducer_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_shop_v1_mqproducer_proto_goTypes = []interface{}{
	(*Products)(nil),                // 0: api.shop.v1.products
	(*CreateMqproducerRequest)(nil), // 1: api.shop.v1.CreateMqproducerRequest
	(*CreateMqproducerReply)(nil),   // 2: api.shop.v1.CreateMqproducerReply
	(*UpdateMqproducerRequest)(nil), // 3: api.shop.v1.UpdateMqproducerRequest
	(*UpdateMqproducerReply)(nil),   // 4: api.shop.v1.UpdateMqproducerReply
	(*DeleteMqproducerRequest)(nil), // 5: api.shop.v1.DeleteMqproducerRequest
	(*DeleteMqproducerReply)(nil),   // 6: api.shop.v1.DeleteMqproducerReply
	(*GetMqproducerRequest)(nil),    // 7: api.shop.v1.GetMqproducerRequest
	(*GetMqproducerReply)(nil),      // 8: api.shop.v1.GetMqproducerReply
	(*ListMqproducerRequest)(nil),   // 9: api.shop.v1.ListMqproducerRequest
	(*ListMqproducerReply)(nil),     // 10: api.shop.v1.ListMqproducerReply
}
var file_api_shop_v1_mqproducer_proto_depIdxs = []int32{
	0,  // 0: api.shop.v1.CreateMqproducerRequest.products:type_name -> api.shop.v1.products
	1,  // 1: api.shop.v1.MqProducer.CreateMqproducer:input_type -> api.shop.v1.CreateMqproducerRequest
	3,  // 2: api.shop.v1.MqProducer.UpdateMqproducer:input_type -> api.shop.v1.UpdateMqproducerRequest
	5,  // 3: api.shop.v1.MqProducer.DeleteMqproducer:input_type -> api.shop.v1.DeleteMqproducerRequest
	7,  // 4: api.shop.v1.MqProducer.GetMqproducer:input_type -> api.shop.v1.GetMqproducerRequest
	9,  // 5: api.shop.v1.MqProducer.ListMqproducer:input_type -> api.shop.v1.ListMqproducerRequest
	2,  // 6: api.shop.v1.MqProducer.CreateMqproducer:output_type -> api.shop.v1.CreateMqproducerReply
	4,  // 7: api.shop.v1.MqProducer.UpdateMqproducer:output_type -> api.shop.v1.UpdateMqproducerReply
	6,  // 8: api.shop.v1.MqProducer.DeleteMqproducer:output_type -> api.shop.v1.DeleteMqproducerReply
	8,  // 9: api.shop.v1.MqProducer.GetMqproducer:output_type -> api.shop.v1.GetMqproducerReply
	10, // 10: api.shop.v1.MqProducer.ListMqproducer:output_type -> api.shop.v1.ListMqproducerReply
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_api_shop_v1_mqproducer_proto_init() }
func file_api_shop_v1_mqproducer_proto_init() {
	if File_api_shop_v1_mqproducer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_shop_v1_mqproducer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Products); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_shop_v1_mqproducer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMqproducerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_shop_v1_mqproducer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMqproducerReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_shop_v1_mqproducer_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateMqproducerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_shop_v1_mqproducer_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateMqproducerReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_shop_v1_mqproducer_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteMqproducerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_shop_v1_mqproducer_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteMqproducerReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_shop_v1_mqproducer_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMqproducerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_shop_v1_mqproducer_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMqproducerReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_shop_v1_mqproducer_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListMqproducerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_shop_v1_mqproducer_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListMqproducerReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_shop_v1_mqproducer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_shop_v1_mqproducer_proto_goTypes,
		DependencyIndexes: file_api_shop_v1_mqproducer_proto_depIdxs,
		MessageInfos:      file_api_shop_v1_mqproducer_proto_msgTypes,
	}.Build()
	File_api_shop_v1_mqproducer_proto = out.File
	file_api_shop_v1_mqproducer_proto_rawDesc = nil
	file_api_shop_v1_mqproducer_proto_goTypes = nil
	file_api_shop_v1_mqproducer_proto_depIdxs = nil
}
