// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"shopp/internal/conf"
	"shopp/internal/server"
	"shopp/internal/service"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, data *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	mqProducerService := service.NewMqProducerService()
	grpcServer := server.NewMqProducerGRPCServer(confServer, mqProducerService, logger)
	app := newApp(logger, grpcServer)
	return app, func() {
	}, nil
}
